# Generated by Django 4.1.7 on 2023-05-24 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import retailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wholesaler', '0005_alter_productmodel_product_wgt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='', max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('product_category', models.CharField(max_length=200)),
                ('product_wgt', models.PositiveIntegerField(null=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='products/cart/', verbose_name='products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='', max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_wgt', models.PositiveIntegerField(null=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='products/cart', verbose_name='products')),
            ],
        ),
        migrations.CreateModel(
            name='RetailorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('password', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='', max_length=200)),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_agent', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=500)),
                ('date_placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_delivery', models.DateTimeField(default=retailer.models.OrderModel.get_future_date)),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('processing', 'Processing'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.productmodel')),
            ],
        ),
    ]
