# Generated by Django 4.1.7 on 2023-05-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0005_alter_productmodel_product_wgt'),
        ('retailer', '0002_ordermodel_product_img1_ordermodel_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.wholesalermodel'),
        ),
    ]
