# Generated by Django 4.2.2 on 2023-06-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_alter_ordermodel_seller_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.retailormodel')),
            ],
        ),
    ]
