# Generated by Django 4.2.2 on 2023-06-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_testimonialsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialsModel',
        ),
    ]
