# Generated by Django 4.1.7 on 2023-05-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WholesalerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('password', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('available_qty', models.DecimalField(decimal_places=0, max_digits=2)),
                ('product_wgt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_des', models.TextField(verbose_name='Description')),
                ('product_purity', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='products')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.categorymodel')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.wholesalermodel')),
            ],
        ),
    ]
