# Generated by Django 4.1.7 on 2023-05-16 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0002_alter_productmodel_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='available_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
