# Generated by Django 4.1.7 on 2023-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0003_alter_productmodel_available_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='available_qty',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
