# Generated by Django 4.2.2 on 2023-06-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0006_latestproductscollectionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestProductsCollectionModel',
        ),
    ]
