# Generated by Django 4.2.2 on 2023-06-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_subscribermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
